---
AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  This template deploys a Citrix Virtual Apps Service Resource Location.
  **WARNING** This template creates Amazon EC2 Windows instance and related resources. You will be billed for the
  AWS resources used if you create a stack from this template. (qs-1p6u9q6o0)
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Citrix Cloud Configuration
        Parameters:
          - CitrixCustomerId
          - CitrixAPIClientID
          - CitrixAPIClientSecret
          - CitrixCloudConnector1HostName
          - CitrixCloudConnector2HostName
          - CitrixVDAHostName

      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - KeyPairName
          - CitrixCloudConnectorInstanceType
          - CitrixVDAInstanceType
          - CitrixVDAServerSetupFileLocation
      - Label:
          default: Microsoft Active Directory Configuration
        Parameters:
          - ADServer1PrivateIP
          - ADServer2PrivateIP
          - DomainDNSName
          - DomainNetBIOSName
          - DomainAdminPassword
      - Label:
          default: Network Configuration
        Parameters:
          - VPCID
          - PrivateInfraSubnet1ID
          - PrivateInfraSubnet2ID
          - PrivateVDASubnet1ID
          - BastionSecurityGroupID

      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix


    ParameterLabels:
      ADServer1PrivateIP:
        default: Active Directory Server 1 IP address
      ADServer2PrivateIP:
        default: Active Directory Server 2 IP address
      BastionSecurityGroupID:
        default: Bastion security group ID
      CitrixAPIClientID:
        default: Citrix Cloud Secure Client ID
      CitrixAPIClientSecret:
        default: Citrix Cloud Secure Client Secret
      CitrixCloudConnector1HostName:
        default: Citrix Cloud Connector 1 name
      CitrixCloudConnector2HostName:
        default: Citrix Cloud Connector 2 name
      CitrixVDAHostName:
        default: Citrix VDA name
      CitrixVDAServerSetupFileLocation:
        default: Citrix VDA server setup file location
      CitrixCloudConnectorInstanceType:
        default: Citrix Cloud Connector instance type
      CitrixCustomerId:
        default: Citrix Cloud Customer ID
      DomainAdminPassword:
        default: Domain admin password
      DomainDNSName:
        default: Domain DNS name
      DomainNetBIOSName:
        default: Domain NetBIOS name
      KeyPairName:
        default: Key pair name
      PrivateInfraSubnet1ID:
        default: Private Citrix infrastructure subnet 1 ID
      PrivateInfraSubnet2ID:
        default: Private Citrix infrastructure subnet 2 ID
      PrivateVDASubnet1ID:
        default: Private Citrix VDA subnet 1 ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      CitrixVDAInstanceType:
        default: Citrix Server VDA instance type
      VPCID:
        default: VPC ID

Parameters:
  ADServer1PrivateIP:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Description: >-
      IP address of the first Active Directory server located in Availability Zone 1.
    Type: String
  ADServer2PrivateIP:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Description: >-
      IP address of the second Active Directory server located in Availability Zone 2.
    Type: String
  BastionSecurityGroupID:
    Description: ID of the Bastion Security Group; e.g., sg-7f16e910.
    Type: 'AWS::EC2::SecurityGroup::Id'
  CitrixAPIClientID:
    Description: ID of your Citrix Cloud Secure Client used for integration with Citrix Cloud APIs.
    Type: String
    NoEcho: 'true'
  CitrixAPIClientSecret:
    Description: Secret of your Citrix Cloud Secure Client.
    Type: String
    NoEcho: 'true'
  CitrixCloudConnector1HostName:
    Description: Host name of the first Citrix Cloud Connector.
    Type: String
    Default: CTX-CC1
    MaxLength: '10'
    MinLength: '1'
  CitrixCloudConnector2HostName:
    Description: Host name of the second Citrix Cloud Connector.
    Type: String
    Default: CTX-CC2
    MaxLength: '10'
    MinLength: '1'
  CitrixVDAHostName:
    Type: String
    Default: CTX-VDA1
    MaxLength: '10'
    MinLength: '1'
    Description: Host name of the Citrix VDA.
  CitrixVDAServerSetupFileLocation:
    Description: >-
      Provide a public URL of the VDAServerSetup_1903.exe file downloaded from
      https://www.citrix.com/downloads/citrix-virtual-apps-and-desktops/product-software/citrix-virtual-apps-and-desktops-1903.html.
      If no value is provided, creation of the VDA Stack will be skipped.
      Note: requiring a public URL is a stop-gap replacement for a previously publicly available VDA setup exe that is now removed.
      https://s3.us-east-2.amazonaws.com/ctxs-vda-installer/vda/VDAServerSetup_1903.exe.
    Type: String
    Default: ""
  CitrixCloudConnectorInstanceType:
    Description: Amazon EC2 instance type for the Citrix Cloud Connector instances.
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.large
      - t3.large
      - m4.large
      - m5.large
  CitrixCustomerId:
    Description: Customer ID of your Citrix Cloud tenant.
    Type: String
  DomainAdminPassword:
    AllowedPattern: >-
      (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: >-
      Password for the domain admin user. Must be at least 8 characters
      and contain letters, numbers, and symbols.
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    Default: example.com
    Description: >-
      Fully qualified domain name (FQDN) of the forest root domain; e.g., example.com.
    MaxLength: '255'
    MinLength: '2'
    Type: String
  DomainNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: example
    Description: >-
      NetBIOS name of the domain (up to 15 characters) for users of earlier
      versions of Windows; e.g., example.
    MaxLength: '15'
    MinLength: '1'
    Type: String
  KeyPairName:
    Description: >-
      Name of an existing Amazon EC2 public/private key pair to enable remote
      access to instances.
    Type: 'AWS::EC2::KeyPair::KeyName'
  PrivateInfraSubnet1ID:
    Description: ID of the private infrastructure subnet 1 in Availability Zone 1; e.g., subnet-a0246dcd.
    Type: 'AWS::EC2::Subnet::Id'
  PrivateInfraSubnet2ID:
    Description: ID of the private infrastructure subnet 2 in Availability Zone 2; e.g., subnet-a0246dce.
    Type: 'AWS::EC2::Subnet::Id'
  PrivateVDASubnet1ID:
    Description: ID of the private VDA subnet 1 in Availability Zone 1; e.g., subnet-a0246dcf.
    Type: 'AWS::EC2::Subnet::Id'
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-ia
    Description: >-
      S3 bucket name for the Quick Start assets. This bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-), but should
      not start or end with a hyphen. You can specify your own bucket if you
      copy all of the assets and submodules into it, if you want to override the
      Quick Start behavior for your specific implementation.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: >-
      The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: cfn-ps-citrix-daas/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  CitrixVDAInstanceType:
    Description: Amazon EC2 instance type for the Citrix VDA instance.
    Type: String
    Default: m5.large
    AllowedValues:
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - g3.4xlarge
      - g3.8xlarge
      - g3.16xlarge
  VPCID:
    Description: ID of the VPC; e.g., vpc-0343606e.
    Type: 'AWS::EC2::VPC::Id'

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-ia']
  CreateVDAStack: !Not [!Equals [!Ref CitrixVDAServerSetupFileLocation, '']]

Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
       !Sub
         - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/citrix-virtualapps-service-iam.yaml'
         - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
           S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

  QSDeploymentID:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/citrix-virtualapps-service-qsdeploymentid.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

  CitrixCloudSecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/citrix-virtualapps-service-securitygroups.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID:                              !Ref VPCID
        BastionSecurityGroupID:             !Ref BastionSecurityGroupID
        QSDeploymentID:                     !GetAtt QSDeploymentID.Outputs.ParameterQSDeploymentID

  CitrixCloudConnectors:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/citrix-virtualapps-service-connectors.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        ADServer1PrivateIP:                   !Ref ADServer1PrivateIP
        ADServer2PrivateIP:                   !Ref ADServer2PrivateIP
        CitrixAPIClientID:                          !Ref CitrixAPIClientID
        CitrixAPIClientSecret:                      !Ref CitrixAPIClientSecret
        CitrixCloudConnector1HostName:        !Ref CitrixCloudConnector1HostName
        CitrixCloudConnector2HostName:        !Ref CitrixCloudConnector2HostName
        CitrixCloudConnectorInstanceType:           !Ref CitrixCloudConnectorInstanceType
        CitrixCloudConnectorSecurityGroup:          !GetAtt CitrixCloudSecurityGroups.Outputs.CCSecurityGroup
        CitrixCustomerId:                           !Ref CitrixCustomerId
        DomainNetBIOSName:                    !Ref DomainNetBIOSName
        DomainDNSName:                        !Ref DomainDNSName
        DomainAdminPassword:                  !Ref DomainAdminPassword
        DomainAdminUser:                      'admin'
        KeyPairName:                          !Ref KeyPairName
        PrivateInfraSubnet1:                  !Ref PrivateInfraSubnet1ID
        PrivateInfraSubnet2:                  !Ref PrivateInfraSubnet2ID
        QSDeploymentID:                     !GetAtt QSDeploymentID.Outputs.ParameterQSDeploymentID
        QSS3BucketName:                       !Ref QSS3BucketName
        QSS3BucketRegion:                     !Ref QSS3BucketRegion
        QSS3KeyPrefix:                        !Ref QSS3KeyPrefix

  VDA:
    Type: AWS::CloudFormation::Stack
    Condition: CreateVDAStack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/citrix-virtualapps-service-vda-serveros.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        ADServer1PrivateIP:                   !Ref ADServer1PrivateIP
        ADServer2PrivateIP:                   !Ref ADServer2PrivateIP
        CitrixAPIClientID:                          !Ref CitrixAPIClientID
        CitrixAPIClientSecret:                      !Ref CitrixAPIClientSecret
        CitrixCustomerId:                           !Ref CitrixCustomerId
        CitrixDeliveryController1HostName:        !GetAtt CitrixCloudConnectors.Outputs.CitrixCloudConnector1HostName
        CitrixDeliveryController2HostName:        !GetAtt CitrixCloudConnectors.Outputs.CitrixCloudConnector2HostName
        CitrixHostingConnectionAWSIAMAccessKey:                !GetAtt IAM.Outputs.ParameterKeyAccessKey
        CitrixHostingConnectionAWSIAMSecretKey:                !GetAtt IAM.Outputs.ParameterKeySecretKey
        CitrixVDAHostName:                    !Ref CitrixVDAHostName
        CitrixVDAInstanceType:                    !Ref CitrixVDAInstanceType
        CitrixVDASecurityGroup:                   !GetAtt CitrixCloudSecurityGroups.Outputs.VDASecurityGroup
        CitrixVDAServerSetupFileLocation:   !Ref CitrixVDAServerSetupFileLocation
        DomainNetBIOSName:                  !Ref DomainNetBIOSName
        DomainDNSName:                      !Ref DomainDNSName
        DomainAdminPassword:                !Ref DomainAdminPassword
        KeyPairName:                        !Ref KeyPairName
        PrivateVDASubnet1:                  !Ref PrivateVDASubnet1ID
        QSDeploymentID:                     !GetAtt QSDeploymentID.Outputs.ParameterQSDeploymentID
        QSS3BucketName:                     !Ref QSS3BucketName
        QSS3BucketRegion:                   !Ref QSS3BucketRegion
        QSS3KeyPrefix:                      !Ref QSS3KeyPrefix


Outputs:
  CitrixResourceLocation:
    Description: Citrix Cloud Resource Location
    Value: !GetAtt CitrixCloudConnectors.Outputs.CitrixResourceLocation
  CitrixCloudConnector1HostName:
    Description: Citrix Cloud Connector 1 Host Name
    Value: !GetAtt CitrixCloudConnectors.Outputs.CitrixCloudConnector1HostName
  CitrixCloudConnector2HostName:
    Description: Citrix Cloud Connector 2 Host Name
    Value: !GetAtt CitrixCloudConnectors.Outputs.CitrixCloudConnector2HostName
  CitrixHostingConnectionName:
    Condition: CreateVDAStack
    Description: Citrix Hosting Connection Name
    Value: !GetAtt VDA.Outputs.CitrixHostingConnectionName
  CitrixCatalogName:
    Condition: CreateVDAStack
    Description: Citrix Catalog Name
    Value: !GetAtt VDA.Outputs.CitrixCatalogName
  CitrixDeliveryGroupName:
    Condition: CreateVDAStack
    Description: Citrix Delivery Group Name
    Value: !GetAtt VDA.Outputs.CitrixDeliveryGroupName
  CitrixVDAHostName:
    Condition: CreateVDAStack
    Description: Citrix VDA Host Name
    Value: !GetAtt VDA.Outputs.CitrixVDAHostName